services:
  samba-ts:
    image: tailscale/tailscale:latest
    container_name: samba-ts
    hostname: mr-samba
    environment:
      #  - TS_AUTHKEY=value
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-tags=tag:samba
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    ports:
      - 445:445
    cap_add:
      - net_admin
      - sys_module

  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}samba/smb.conf:/etc/samba/smb.conf
      - ${CONFIGS}samba/users.conf:/etc/samba/users.conf
      - ${DATA}:/storage
    depends_on:
      - samba-ts
    network_mode: service:samba-ts
    restart: always
