---
services:
  filebrowser-ts:
    image: tailscale/tailscale:latest
    container_name: filebrowser-ts
    hostname: filebrowser
    environment:
      #  - TS_AUTHKEY=value
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_EXTRA_ARGS=--advertise-tags=tag:filebrowser
      - TZ=Asia/Dubai
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - TZ=Asia/Dubai
      - PUID=1000
      - PGID=1000
    volumes:
      - ${CONFIGS}filebrowser:/config
      - ${DATA}:/srv
      - ${CONFIGS}filebrowser_db:/database
    depends_on:
      - filebrowser-ts
    network_mode: service:filebrowser-ts
    restart: unless-stopped
