configs:
  jellyfin-ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8096"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  jellyfin-ts:
    image: tailscale/tailscale:latest
    container_name: jellyfin-ts
    hostname: mr-jellyfin
    environment:
      - TS_AUTHKEY=${AUTH}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    configs:
      - source: jellyfin-ts-serve
        target: /config/serve.json
    volumes:
      - ${PWD}/state:/var/lib/tailscale
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}jellyfin:/config
      - ${DATA}tvshows:/data/tvshows
      - ${DATA}movies:/data/movies
    network_mode: service:jellyfin-ts
    restart: unless-stopped
