configs:
  copyparty-ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:3923"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

  copyparty-config:
    content: |
      [global]
      e2dsa
      rproxy: -1

      [accounts]
      shimmer:changeme
      guest:changeme2

      [/courses]
      /data/courses
      accs:
        rw: shimmer
        r: guest

      [/wallpapers]
      /data/wallpapers
      accs:
        rw: shimmer
        r: guest

      [/sw]
      /data/sw
      accs:
        rw: shimmer
        r: guest

      [/upload]
      /data/upload
      accs:
        rw: shimmer
        rw: guest

      [/workouts]
      /data/workouts
      accs:
        rw: shimmer
        r: guest

services:
  copyparty-ts:
    image: tailscale/tailscale:latest
    container_name: copyparty-ts
    hostname: copyparty
    environment:
      - TS_AUTHKEY=${AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=true
    configs:
      - source: copyparty-ts-serve
        target: /config/serve.json
    volumes:
      - ${PWD}/state:/var/lib/tailscale
    restart: unless-stopped

  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    network_mode: service:copyparty-ts
    configs:
      - source: copyparty-config
        target: /cfg/config.conf
    volumes:
      - ${DATA}:/data
    restart: unless-stopped
